# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('is_votable', models.BooleanField(default=False)),
                ('color', models.CharField(default='#999999', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=1000)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panda.ForumCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_by', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_parent', to='panda.ForumComment')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('extract', models.CharField(default='Extract missing', max_length=1000)),
                ('site', models.URLField(null=True)),
                ('date', models.DateField(null=True)),
                ('catergory', models.CharField(choices=[('ACT', 'Action'), ('ADV', 'Adventure'), ('ROL', 'Roleplaying'), ('MMO', 'MMO'), ('FPS', 'FPS'), ('SPO', 'Sport'), ('MOB', 'MOBA')], default='NON', max_length=3)),
                ('picture', models.ImageField(blank=True, upload_to='game_images')),
                ('steam_id', models.IntegerField(blank=True, default=None, null=True)),
                ('rating', models.FloatField(default=-1)),
                ('Playstation', models.BooleanField(default=False)),
                ('Xbox', models.BooleanField(default=False)),
                ('PC', models.BooleanField(default=False)),
                ('Nintendo', models.BooleanField(default=False)),
                ('Mobile', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('comments', models.ManyToManyField(blank=True, to='panda.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='GameRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameStudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('TwitterHandle', models.CharField(blank=True, max_length=15, null=True)),
                ('picture', models.ImageField(blank=True, upload_to='studio_images')),
                ('slug', models.SlugField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bio', models.CharField(blank=True, max_length=500, null=True)),
                ('Steam', models.CharField(blank=True, max_length=31, null=True)),
                ('PSN', models.CharField(blank=True, max_length=16, null=True)),
                ('Xbox', models.CharField(blank=True, max_length=15, null=True)),
                ('Nintendo', models.CharField(blank=True, max_length=10, null=True)),
                ('rating', models.FloatField(default=-1.0)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user_votes', models.IntegerField(default='0')),
                ('user_roles', models.CharField(choices=[('Admin', 'Admin'), ('Publisher', 'Publisher')], max_length=10)),
                ('approved', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='panda.Player')),
                ('rated_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_player', to='panda.Player')),
            ],
        ),
        migrations.CreateModel(
            name='ReportingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panda.Player')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Disabled', 'Disabled')], max_length=10)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('no_of_views', models.IntegerField(default='0')),
                ('slug', models.SlugField(max_length=1000)),
                ('no_of_likes', models.IntegerField(default='0')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panda.ForumCategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('U', 'Up'), ('D', 'Down')], max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='votes',
            field=models.ManyToManyField(to='panda.Vote'),
        ),
        migrations.AddField(
            model_name='gamerating',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panda.Player'),
        ),
        migrations.AddField(
            model_name='gamerating',
            name='rated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panda.Game'),
        ),
        migrations.AddField(
            model_name='game',
            name='comp_players',
            field=models.ManyToManyField(blank=True, related_name='comp', to='panda.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='casual', to='panda.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='recommend',
            field=models.ManyToManyField(blank=True, related_name='_game_recommend_+', to='panda.Game'),
        ),
        migrations.AddField(
            model_name='game',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panda.GameStudio'),
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_comments', to='panda.Topic'),
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='votes',
            field=models.ManyToManyField(to='panda.Vote'),
        ),
        migrations.AddField(
            model_name='comment',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panda.Player'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panda.Player'),
        ),
    ]
