# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panda.ForumCategory'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.FloatField(default=-1),
        ),
    ]
