# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='extract',
            field=models.CharField(default='Extract missing', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gamestudio',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='Bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
