# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.FloatField(default=-1.0),
        ),
    ]
