# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panda.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='comment',
            field=models.ManyToManyField(blank=True, to='panda.Comment'),
        ),
    ]
