# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 22:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0002_auto_20180320_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcategory',
            name='color',
            field=models.CharField(default='#999999', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
