# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panda', '0002_auto_20180227_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='Mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='Nintendo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='PC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='Playstation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='Xbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='catergory',
            field=models.CharField(choices=[('NON', 'None'), ('ACT', 'Action'), ('ADV', 'Adventure'), ('ROL', 'Roleplaying'), ('MMO', 'MMO'), ('FPS', 'FPS'), ('SPO', 'SPO')], default='NON', max_length=3),
        ),
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='extract',
            field=models.CharField(default='Extract missing', max_length=500),
        ),
        migrations.AddField(
            model_name='game',
            name='site',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='gamestudio',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, to='panda.Player'),
        ),
    ]
