# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0002_auto_20180322_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='approvedAccount',
            field=models.BooleanField(default=False),
        ),
    ]
