# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0002_auto_20180301_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='comment',
            new_name='comments',
        ),
    ]
