# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0003_auto_20180228_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='blank', unique=True),
            preserve_default=False,
        ),
    ]
