# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0004_auto_20180302_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestudio',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
