# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0004_auto_20180322_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='approvedAccount',
            new_name='approved',
        ),
    ]
