# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-03 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0005_auto_20180302_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='picture',
            field=models.ImageField(blank=True, upload_to='game_images'),
        ),
    ]
