# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0005_auto_20180322_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panda.Player')),
            ],
        ),
    ]
