# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0006_auto_20180303_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steam_id',
            field=models.IntegerField(default=-1),
        ),
    ]
