# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0006_requestapproval'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestApproval',
            new_name='ApprovalRequest',
        ),
    ]
