# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0007_game_steam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='steam_id',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
