# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0008_auto_20180304_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='steam_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
