# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0008_game_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='catergory',
            field=models.CharField(choices=[('ACT', 'Action'), ('ADV', 'Adventure'), ('ROL', 'Roleplaying'), ('MMO', 'MMO'), ('FPS', 'FPS'), ('SPO', 'Sport'), ('MOB', 'MOB')], default='NON', max_length=3),
        ),
    ]
