# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0009_auto_20180304_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.FloatField(default=-1.0),
        ),
    ]
