# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0011_reportingmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='comp_players',
            field=models.ManyToManyField(blank=True, related_name='comp', to='panda.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='casual', to='panda.Player'),
        ),
    ]
