# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0012_auto_20180320_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestudio',
            name='TwitterHandle',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='gamestudio',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gamestudio',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
